version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build-and-tests:
    executor: 'node/default'
    steps:
      - checkout
      - run: node --version
      - node/install:
          node-version: '12'
          install-yarn: true
      - run: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-tests