version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  build-and-tests:
    executor: 'node/default'
    environment:
      API_KEY: $API_KEY
      AUTH_DOMAIN: $AUTH_DOMAIN
      DATABASE_URL: $DATABASE_URL
      PROJECT_ID: $PROJECT_ID
      STORAGE_BUCKET: $STORAGE_BUCKET
      MESSAGING_SENDER_ID: $MESSAGING_SENDER_ID
      APP_ID: $APP_ID
      MEASUREMENT_ID: $MEASUREMENT_ID
    steps:
      - checkout
      - run: node --version
      - node/install:
          node-version: '12.11.1'
          install-yarn: true
      - run:
          name: update gcc to v9
          command: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt update && sudo apt install gcc-9
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install firebase tools
          command: npm install -D firebase-tools
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: check env var
          command: echo $API_KEY
      - run:
          name: build
          command: npm run build 
      - store_artifacts:
          path: ./public
      - run:
          name: Firebase Deploy
          command: pwd && ls -la && ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project bangkok-biennial
  deploy:
    executor: 'node/default'
    steps:
      - checkout

workflows:
    build-and-test:
      jobs:
        - build-and-tests
