version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tags: '12'
    steps:
      - checkout
      - node/install-packages:
        - pkg-manager: yarn
      - yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-tests