const NEW_USER = 'NEW'
const FINISHED_BASIC = 'FINISHED_BASIC'
const FINISHED_ADVANCE = 'FINISHED_ADVANCE'
const PUBLIC = 'PUBLIC'

export default {
  NEW_USER,
  FINISHED_BASIC,
  FINISHED_ADVANCE,
  PUBLIC,
}
